'use client'
import{useEffect,useState,useCallback,useRef}from'react'
import{createClientComponentClient}from'@supabase/auth-helpers-nextjs'
import{useRouter}from'next/navigation'
interface Paciente{id:string;nome:string;endereco?:string;bairro?:string;lat?:number;lng?:number}
interface Passenger{id:string;paciente:Paciente;ordem:number;status:string;est_pickup_at?:string}
interface Hospital{id:string;nome:string;cidade?:string;lat?:number;lng?:number}
interface Leg{id:string;hospital:Hospital;horario_saida:string;ordem:number;status:string;passengers:Passenger[];est_departure_at?:string;est_hospital_at?:string;est_outbound_min?:number}
interface Plan{id:string;data:string;status:string;veiculo:{id:string;placa:string;modelo?:string};motorista:{id:string;nome:string};legs:Leg[]}
interface PendingAction{passId:string;status:string;oldStatus:string;nome:string;label:string}
const TZ='America/Sao_Paulo'
function fmtHora(iso?:string|null,fb?:string){if(iso)return new Date(iso).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:TZ});if(fb)return fb.substring(0,5);return'--:--'}
function mapsUrl(p:Paciente){if(p.lat&&p.lng)return'https://www.google.com/maps?q='+p.lat+','+p.lng;const a=[p.endereco,p.bairro].filter(Boolean).join(', ');return a?'https://www.google.com/maps/search/'+encodeURIComponent(a):'#'}
function Countdown({targetIso}:{targetIso:string}){const[diff,setDiff]=useState(0);useEffect(()=>{const t=new Date(targetIso).getTime();const tick=()=>setDiff(Math.max(0,Math.floor((t-Date.now())/1000)));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[targetIso]);if(diff<=0)return<span className="text-green-400 font-bold text-3xl animate-pulse">Hora de sair!</span>;const h=Math.floor(diff/3600),m=Math.floor((diff%3600)/60),s=diff%60;return<span className="font-mono font-bold text-4xl text-blue-300 tracking-widest">{h>0&&h+':'}{String(m).padStart(2,'0')}:{String(s).padStart(2,'0')}</span>}
const SC:Record<string,{label:string;color:string;bg:string}>={aguardando:{label:'Aguardando',color:'text-yellow-400',bg:'bg-yellow-400/10 border-yellow-400/30'},embarcou:{label:'Embarcou',color:'text-green-400',bg:'bg-green-400/10 border-green-400/30'},liberado:{label:'Liberado',color:'text-blue-400',bg:'bg-blue-400/10 border-blue-400/30'},outro_motorista:{label:'Outro Motorista',color:'text-orange-400',bg:'bg-orange-400/10 border-orange-400/30'},desistiu:{label:'Desistiu',color:'text-red-400',bg:'bg-red-400/10 border-red-400/30'},ausente:{label:'Ausente',color:'text-gray-400',bg:'bg-gray-400/10 border-gray-400/30'}}
const STATUS_ROTA:Record<string,string>={draft:'Aguardando inicio',active:'Em andamento',returning:'Retornando a base',completed:'Finalizada'}
const ACTION_LABELS:Record<string,string>={liberado:'Liberado',outro_motorista:'Outro motorista ira buscar',desistiu:'Desistiu'}
export default function MotoristaPage(){
  const sb=createClientComponentClient();const router=useRouter()
  const[user,setUser]=useState<any>(null);const[nomePerfil,setNomePerfil]=useState('')
  const _d0=new Date();const _t0=_d0.getFullYear()+'-'+String(_d0.getMonth()+1).padStart(2,'0')+'-'+String(_d0.getDate()).padStart(2,'0')
  const[dataVis,setDataVis]=useState(_t0)
  const[plans,setPlans]=useState<Plan[]>([]);const[sel,setSel]=useState<Plan|null>(null)
  const[loading,setLoading]=useState(true);const[gpsAtivo,setGpsAtivo]=useState(false)
  const[atualiz,setAtualiz]=useState<Record<string,boolean>>({});const[salvLoc,setSalvLoc]=useState<Record<string,boolean>>({})
  const[modalProb,setModalProb]=useState(false);const[formProb,setFormProb]=useState({tipo:'outro',urgencia:'normal',descricao:''})
  const[enviando,setEnviando]=useState(false);const[pending,setPending]=useState<PendingAction|null>(null)
  const posAtual=useRef<GeolocationPosition|null>(null)
  const carregar=useCallback(async(uid?:string,dataParam?:string)=>{
    const userId=uid||user?.id;if(!userId){setLoading(false);return}
    const hoje=dataParam||(()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')})()
    try{const{data}=await sb.from('route_plans').select('id,data,status,veiculo:veiculos(id,placa,modelo),motorista:profiles(id,nome),route_legs(id,horario_saida,ordem,status,est_departure_at,est_hospital_at,est_outbound_min,hospital:hospitais(id,nome,cidade,lat,lng),leg_passengers(id,ordem,status,est_pickup_at,paciente:pacientes(id,nome,endereco,bairro,lat,lng)))').eq('data',hoje).eq('motorista_id',userId).in('status',['draft','active','returning']).order('created_at',{ascending:false})
    if(data&&data.length){const ps:Plan[]=data.map((r:any)=>({...r,legs:((r.route_legs||[])as any[]).sort((a:any,b:any)=>a.ordem-b.ordem).map((l:any)=>({...l,passengers:(l.leg_passengers||[]).sort((a:any,b:any)=>a.ordem-b.ordem)}))}));setPlans(ps);setSel(prev=>prev?ps.find(p=>p.id===prev.id)||null:null)}else{setPlans([])}}catch(e){console.error(e)}
    setLoading(false)
  },[sb,user?.id])
  useEffect(()=>{sb.auth.getUser().then(async({data:{user}})=>{if(!user){setLoading(false);return};setUser(user);const{data:p}=await sb.from('profiles').select('nome').eq('id',user.id).single();if(p)setNomePerfil((p as any).nome||'');carregar(user.id)})},[sb,carregar])
  useEffect(()=>{if(user)carregar(undefined,dataVis)},[dataVis,user])
  useEffect(()=>{if(!user)return;const ch=sb.channel('mot-rt').on('postgres_changes',{event:'*',schema:'public',table:'leg_passengers'},()=>carregar()).on('postgres_changes',{event:'*',schema:'public',table:'route_plans'},()=>carregar()).subscribe();return()=>{sb.removeChannel(ch)}},[sb,user,carregar])
  useEffect(()=>{if(!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>{posAtual.current=p;setGpsAtivo(true)},()=>setGpsAtivo(false),{enableHighAccuracy:true,maximumAge:10000});return()=>navigator.geolocation.clearWatch(id)},[])
  const confirmar=(passId:string,ns:string,os:string,nome:string)=>{setPending({passId,status:ns,oldStatus:os,nome,label:ACTION_LABELS[ns]||ns})}
  const executar=async()=>{if(!pending)return;setAtualiz(p=>({...p,[pending.passId]:true}));await sb.from('leg_passengers').update({status:pending.status}).eq('id',pending.passId);setAtualiz(p=>({...p,[pending.passId]:false}));setPending(null);carregar()}
  const salvarLoc=async(passId:string,pacId:string)=>{if(!posAtual.current)return alert('GPS nao disponivel');setSalvLoc(p=>({...p,[passId]:true}));const{latitude:lat,longitude:lng}=posAtual.current.coords;await sb.from('pacientes').update({lat,lng}).eq('id',pacId);setSalvLoc(p=>({...p,[passId]:false}));alert('Localizacao salva!')}
  const setRotaStatus=async(s:string)=>{if(!sel)return;await sb.from('route_plans').update({status:s}).eq('id',sel.id);carregar()}
  const Header=({onBack}:{onBack?:()=>void})=>(<header className="bg-gray-900 border-b border-gray-700/50 px-4 py-3 flex items-center justify-between sticky top-0 z-10"><div className="flex items-center gap-3">{onBack&&<button onClick={onBack} className="text-blue-400 hover:text-blue-300 text-sm font-medium mr-1">&#8592; Voltar</button>}<span className="text-white font-bold text-lg tracking-wide">Smart<span className="text-blue-400">TFD</span></span><span className="text-xs text-gray-500 bg-gray-800 px-2 py-0.5 rounded">Motorista</span></div><div className="flex items-center gap-3 text-xs"><span className={'flex items-center gap-1 '+(gpsAtivo?'text-green-400':'text-red-400')}><span className={'w-2 h-2 rounded-full '+(gpsAtivo?'bg-green-400 animate-pulse':'bg-red-400')}/>{gpsAtivo?'GPS ativo':'sem GPS'}</span><span className="text-gray-300">{nomePerfil}</span><button onClick={()=>sb.auth.signOut().then(()=>router.push('/login'))} className="text-gray-500 hover:text-red-400">Sair</button></div></header>)
  if(loading)return(<div className="min-h-screen bg-gray-950 flex flex-col items-center justify-center gap-4"><div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"/><p className="text-gray-400 text-sm">Carregando...</p></div>)
  if(sel){
    const leg=sel.legs[0];const totalPax=leg?.passengers?.length||0
    const allDone=!!(leg?.passengers?.length)&&leg.passengers.every(p=>['liberado','desistiu','ausente','outro_motorista'].includes(p.status))
    return(<div className="min-h-screen bg-gray-950 flex flex-col pb-28">
      <Header onBack={()=>setSel(null)}/>
      <div className={'px-4 py-2 text-xs font-semibold flex items-center justify-between '+(sel.status==='active'?'bg-green-900/50 text-green-300':sel.status==='returning'?'bg-orange-900/50 text-orange-300':'bg-blue-900/50 text-blue-300')}><span>{STATUS_ROTA[sel.status]||sel.status}</span><span className="opacity-70">{sel.veiculo?.placa}</span></div>
      <div className="p-4 space-y-4">
        <div className="bg-gray-900 rounded-2xl border border-gray-700/50 p-5"><div className="flex items-start justify-between"><div><p className="text-gray-500 text-xs uppercase tracking-wider mb-1">Saida da garagem</p>{leg?.est_departure_at?<Countdown targetIso={leg.est_departure_at}/>:<div className="text-4xl font-bold font-mono text-blue-300">{fmtHora(null,leg?.horario_saida)}</div>}{leg?.est_outbound_min&&<p className="text-gray-500 text-xs mt-1">~{leg.est_outbound_min} min</p>}</div><div className="text-right"><p className="text-gray-500 text-xs uppercase tracking-wider mb-1">Veiculo</p><p className="text-white font-bold text-lg">{sel.veiculo?.modelo||sel.veiculo?.placa}</p><p className="text-gray-400 text-xs">{sel.veiculo?.placa}</p><p className="text-gray-500 text-xs mt-1">{totalPax} pax</p></div></div>{leg&&<div className="mt-3 pt-3 border-t border-gray-700/50 flex items-center justify-between"><div><p className="text-gray-500 text-xs">Local de consulta</p><p className="text-white text-sm font-medium">{leg.hospital?.nome}</p><p className="text-gray-400 text-xs">{leg.hospital?.cidade}</p></div><div className="text-right"><p className="text-gray-500 text-xs">Horario</p><p className="text-blue-300 text-lg font-bold font-mono">{fmtHora(leg.est_hospital_at,leg.horario_saida)}</p></div></div>}</div>
        {leg&&<div><p className="text-gray-500 text-xs uppercase tracking-wider mb-3 px-1">Pacientes ({totalPax})</p><div className="space-y-3">{leg.passengers.map((pass,idx)=>{const sc=SC[pass.status]||SC['aguardando'];const pac=pass.paciente;const busy=atualiz[pass.id];return(<div key={pass.id} className={'rounded-2xl border p-4 '+sc.bg}><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-blue-600/30 border border-blue-500/30 flex items-center justify-center text-blue-300 font-bold text-sm">{idx+1}</div><div><p className="text-white font-semibold text-sm">{pac?.nome||'Paciente'}</p><span className={'text-xs font-medium '+sc.color}>{sc.label}</span></div></div><a href={mapsUrl(pac)} target="_blank" rel="noreferrer" className="text-xs text-blue-400 border border-blue-500/30 rounded-lg px-2 py-1">Ver mapa</a></div><div className="text-xs text-gray-400 mb-3 space-y-0.5">{pac?.bairro&&<p>&#128205; {pac.bairro}</p>}{pac?.endereco&&<p>&#127968; {pac.endereco}</p>}</div><div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>salvarLoc(pass.id,pac?.id||'')} className={'col-span-2 py-2 rounded-xl text-xs font-medium bg-blue-600/20 border border-blue-500/30 text-blue-300 hover:bg-blue-600/40 disabled:opacity-40'+(salvLoc[pass.id]?' animate-pulse':'')}>Salvar Localizacao</button><button disabled={busy||pass.status==='liberado'} onClick={()=>confirmar(pass.id,'liberado',pass.status,pac?.nome||'')} className="py-2 rounded-xl text-xs font-medium bg-teal-600/20 border border-teal-500/30 text-teal-300 hover:bg-teal-600/40 disabled:opacity-40">Liberado</button><button disabled={busy} onClick={()=>confirmar(pass.id,'outro_motorista',pass.status,pac?.nome||'')} className="py-2 rounded-xl text-xs font-medium bg-orange-600/20 border border-orange-500/30 text-orange-300 hover:bg-orange-600/40 disabled:opacity-40">Outro Mot.</button><button disabled={busy} onClick={()=>confirmar(pass.id,'desistiu',pass.status,pac?.nome||'')} className="col-span-2 py-2 rounded-xl text-xs font-medium bg-red-600/20 border border-red-500/30 text-red-300 hover:bg-red-600/40 disabled:opacity-40">Desistiu</button></div></div>)})}</div><div className="mt-4"><button onClick={()=>setModalProb(true)} className="w-full py-3 rounded-2xl text-sm font-medium bg-red-900/30 border border-red-500/30 text-red-300 hover:bg-red-900/50">Reportar Problema</button></div></div>}
      </div>
      <div className="fixed bottom-0 left-0 right-0 bg-gray-900/95 backdrop-blur border-t border-gray-700/50 p-3"><div className="grid grid-cols-3 gap-2"><button disabled={sel.status!=='draft'} onClick={()=>setRotaStatus('active')} className="py-3 rounded-xl text-xs font-bold bg-green-600 hover:bg-green-700 text-white disabled:opacity-40">Iniciar Rota</button><button disabled={sel.status!=='active'} onClick={()=>setRotaStatus('returning')} className="py-3 rounded-xl text-xs font-bold bg-orange-600 hover:bg-orange-700 text-white disabled:opacity-40">Retornar Base</button><button disabled={sel.status==='completed'||!allDone} onClick={()=>setRotaStatus('completed')} className="py-3 rounded-xl text-xs font-bold bg-blue-600 hover:bg-blue-700 text-white disabled:opacity-40">Finalizar</button></div></div>
      {pending&&(<div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 px-4"><div className="bg-gray-900 border border-gray-700 rounded-2xl w-full max-w-sm p-6 space-y-4"><p className="text-gray-400 text-xs uppercase tracking-wider">Confirmar acao</p><p className="text-white font-semibold text-base">{pending.label}</p><p className="text-gray-400 text-sm">Paciente: <span className="text-white">{pending.nome}</span></p><div className="grid grid-cols-2 gap-3 mt-2"><button onClick={()=>setPending(null)} className="py-3 rounded-xl text-sm font-medium bg-gray-700 hover:bg-gray-600 text-gray-200">Cancelar</button><button onClick={executar} className="py-3 rounded-xl text-sm font-bold bg-blue-600 hover:bg-blue-700 text-white">Confirmar</button></div></div></div>)}
      {modalProb&&(<div className="fixed inset-0 bg-black/80 flex items-end z-50" onClick={()=>setModalProb(false)}><div className="bg-gray-900 rounded-t-3xl w-full p-6 space-y-4" onClick={e=>e.stopPropagation()}><h3 className="text-white font-bold text-lg">Reportar Problema</h3><select value={formProb.tipo} onChange={e=>setFormProb(p=>({...p,tipo:e.target.value}))} className="w-full bg-gray-800 text-white rounded-xl px-4 py-3 text-sm border border-gray-700"><option value="mecanico">Problema mecanico</option><option value="acidente">Acidente</option><option value="pneu">Pneu furado</option><option value="combustivel">Sem combustivel</option><option value="outro">Outro</option></select><select value={formProb.urgencia} onChange={e=>setFormProb(p=>({...p,urgencia:e.target.value}))} className="w-full bg-gray-800 text-white rounded-xl px-4 py-3 text-sm border border-gray-700"><option value="baixa">Urgencia baixa</option><option value="normal">Urgencia normal</option><option value="alta">URGENCIA ALTA</option></select><textarea value={formProb.descricao} onChange={e=>setFormProb(p=>({...p,descricao:e.target.value}))} placeholder="Descreva o problema..." rows={3} className="w-full bg-gray-800 text-white rounded-xl px-4 py-3 text-sm border border-gray-700 resize-none"/><button disabled={enviando} onClick={async()=>{if(!sel||!user)return;setEnviando(true);await sb.from('route_problems').insert({plan_id:sel.id,motorista_id:user.id,...formProb});setEnviando(false);setModalProb(false);alert('Problema reportado!')}} className="w-full py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold disabled:opacity-50">{enviando?'Enviando...':'Enviar Alerta'}</button></div></div>)}
    </div>)
  }
  return(<div className="min-h-screen bg-gray-950 flex flex-col"><Header/><div className="p-4 space-y-3"><div className="bg-gray-900 rounded-2xl border border-gray-700/50 p-3 flex items-center justify-between mb-1">
        <button onClick={()=>{const d=new Date(dataVis+'T12:00:00');d.setDate(d.getDate()-1);setDataVis(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'))}} className="text-blue-400 hover:text-blue-300 text-2xl px-3 py-1">&#8249;</button>
        <div className="text-center">
          <p className="text-white font-bold text-sm">{new Date(dataVis+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'short'})}</p>
          {dataVis===_t0&&<p className="text-blue-400 text-xs">Hoje</p>}
          {dataVis!==_t0&&<button onClick={()=>setDataVis(_t0)} className="text-blue-400 text-xs hover:underline">Ir para hoje</button>}
        </div>
        <button onClick={()=>{const d=new Date(dataVis+'T12:00:00');d.setDate(d.getDate()+1);setDataVis(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'))}} className="text-blue-400 hover:text-blue-300 text-2xl px-3 py-1">&#8250;</button>
      </div>
      <p className="text-gray-500 text-xs uppercase tracking-wider px-1">Rotas de hoje</p>{plans.length===0&&(<div className="flex flex-col items-center justify-center gap-4 py-20"><div className="w-16 h-16 rounded-full bg-gray-800 flex items-center justify-center text-3xl">&#128506;</div><p className="text-white font-bold text-lg">Sem rotas para hoje</p><p className="text-gray-400 text-sm text-center">Nenhuma rota foi atribuida a voce.</p><button onClick={()=>carregar()} className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-medium">Verificar novamente</button></div>)}{plans.map(p=>{const leg=p.legs[0];const total=leg?.passengers?.length||0;const sc=p.status==='active'?'border-green-500/40 bg-green-900/10':p.status==='returning'?'border-orange-500/40 bg-orange-900/10':'border-gray-700/50 bg-gray-900';return(<button key={p.id} onClick={()=>setSel(p)} className={'w-full text-left rounded-2xl border p-4 transition-all hover:border-blue-500/50 '+sc}><div className="flex items-start justify-between mb-2"><div><p className="text-white font-bold text-2xl font-mono">{fmtHora(null,leg?.horario_saida)}</p><p className="text-gray-500 text-xs">saida da garagem</p></div><span className={'text-xs px-2 py-1 rounded-full font-medium '+(p.status==='active'?'bg-green-900/50 text-green-300':p.status==='returning'?'bg-orange-900/50 text-orange-300':'bg-blue-900/50 text-blue-300')}>{STATUS_ROTA[p.status]||p.status}</span></div><div className="flex items-center justify-between text-xs text-gray-400"><span>{leg?.hospital?.nome||'Hospital'}</span><span>{p.veiculo?.modelo||p.veiculo?.placa}</span><span>{total} pax</span></div><div className="mt-2 text-right text-xs text-blue-400 font-medium">Ver rota &#8594;</div></button>)})}</div></div>)
}